sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "wirecard"

php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
  - secure: ${SONAR_TOKEN}
  - COMPOSER_ARGS="--no-interaction"
  - github_token:
      secure: "Iy/Plz3V++TKSQbz/A0x7ZhETSfcvbXxT4zKQh51W8fjBUlKKrQmDA1rICIjnfFs0bNAe6M2yQxxHgJKUJPBsi9Nk/Ynuk/I5lLK1jLL6THioGB6oKUyRBytlcVLZ+0lNqmV/jRKYdwEPI+jNduCk5GSjubSGMIWGNDcqAUiTu+oy3Gu9FS/auEGxim7UaZYC+MM+7ir0zD6w/0nuCaxalAeLahFz0g3QlXc7FB88SxH//lxzKDZh3U6XKyIEXGG8IQiCYaJRUqr9unzHDVbjOvNT6HWZQ4jGSfnCZTnp4aPfOrk1Ir334/4Cuy4xCP4iiuiRFHoxw++uknh77slUwRtZbrUlwoCbvT0V/GOQaN2HSjrTOc5n1/M0XsPRumbZ+I/4EoCnZUwNiBpWtVhrzSpE84+0BBj67gmStzca1sZMkts+oHnr5S6qajVY5ePY4Sn3rI/JbUJP501zexRHgqKY26a+Hqz9TAnNJqRKfm6ez5pSlXUKk4eCl7slgYuY8I="


before_install:
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  - git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
  - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
  - $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR

install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - sonar-scanner
  - $PHPCS_DIR/bin/phpcs -p --ignore=*/Test/*,*/vendor/* . --standard=WordPress-Core

after_script:
  - travis_retry composer upload-coverage
