sudo: false
dist: trusty
language: php

cache:
 directories:
  - $HOME/.sonar/cache
  
php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis-retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - sonar-scanner
  - composer cs-check

after_script:
  - composer upload-coverage